services:
  backend:
    build:
      context: backend
    ports:
      - 6401:3000

  rethinkdb:
    image: rethinkdb:latest
    volumes:
      - leware_database:/data
    ports:
      - 6403:8080

volumes:
  leware_database:
